name: Update Exchange Rate

on:
  schedule:
    - cron: '0 6 * * *'  # Runs at 18:00 UTC daily
  workflow_dispatch:  # Allows manual triggers

jobs:
  update-rate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create credentials file
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' | base64 --decode > credentials.json

    - name: Verify credentials file
      run: |
        if [ ! -s credentials.json ]; then
          echo "Error: credentials.json is empty"
          exit 1
        fi
        if ! jq empty credentials.json 2>/dev/null; then
          echo "Error: credentials.json is not valid JSON"
          exit 1
        fi
    
    - name: Run script
      run: python exchange_rate_to_sheets.py
      env:
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    - name: Clean up credentials
      if: always()
      run: rm -f credentials.json
