name: Update Exchange Rate

on:
  schedule:
    - cron: '0 6 * * *'  # Runs at 18:00 UTC daily
  workflow_dispatch:  # Allows manual triggers

jobs:
  update-rate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create credentials file
      run: |
        echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json
    
    - name: Run script
      run: python exchange_rate_to_sheets.py
      env:
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    - name: Clean up credentials
      run: rm -f credentials.json
